### ISSUE TITLE
Load example script to adapt to CosmoPower-JAX

### ISSUE THREAD

**Issue by dpiras** [cosmopower-organization/jense_2024_emulators#1]
Hey @HTJense @borisbolliet, 

 @Lbalkenhol would like to use some of the models here in his pipeline (particularly the neutrino ones). He was trying to open them with `CosmoPower-JAX`, and reached out to me as he was getting some errors. After some investigation I think the problem is in the format of the dictionary used to store these models.

Could you please provide an example script of how you load these models, so that I can reproduce it in `CPJ`?

Thank you!

**Comment by dpiras** [comment]
(note that this still seems relevant to me, as the file formats seem different than what shown [here](https://github.com/cosmopower-organization/mnu/issues/1)?)

**Comment by borisbolliet** [comment]
Yes you are right! I think it should be very similar though because I used some of @HTJense's scripts to make the script I sent [here](https://github.com/cosmopower-organization/mnu/issues/1#issuecomment-2434770732). 

Let us extend the examples to these emulators as well and get back to you. Will be very useful.

**Comment by dpiras** [comment]
I think I was able to edit `CPJ` to load the models ([see here the PR](https://github.com/dpiras/cosmopower-jax/pull/11)). I get something like this for TT, EE and TE; do they make sense for the models I'm loading?
![image](https://github.com/user-attachments/assets/828834da-c44d-4cdb-bccd-75164874a24e)
![image](https://github.com/user-attachments/assets/24cfaed6-d500-4bd6-8f11-46bd1114aee6)
![image](https://github.com/user-attachments/assets/a194dc8c-f0e6-4967-91f7-df11454776b2)


I'll wait to hear what you think before deploying the new version of CPJ. I'll also wait to clarify the [other issue](https://github.com/cosmopower-organization/mnu/issues/1). @Lbalkenhol feel also free to comment if something looks weird.

As a final note, it would be nice to have a uniform format to save and load files in the future, so that we don't need to take into account all possible cases -- flagging this for the packaging being done [here](https://github.com/alessiospuriomancini/cosmopower/pull/28).

**Comment by Lbalkenhol** [comment]
Hi guys, thank you for jumping on this so quickly and thank you for making the models public! I switched to the experimental CPJ branch Davide coded up and it works for me, I can even load them into the corresponding [candl wrapper](https://candl.readthedocs.io/en/latest/interface/interface_theory.html#cosmopower-jax) out of the box without crashing. Quick question regarding the predictions produced by @HTJense and @borisbolliet 's models though. As I understand these are dimensionless power spectra. How do I get access to the CMB temperature to scale them to "normal" muK^2 CMB units? I can't seem to find the right value in the emulator attribues, .yaml file, neither is it part of the predictions of the corresponding derived parameter model. Cheers!

**Comment by Lbalkenhol** [comment]
and adding to this, it would be amazing to also have the models for derived parameters, sigma8, etc. work in CosmoPower-JAX. I haven't encountered a crash naively playing with them, but some weird predictions (e.g. infs). Perhaps I'm just inputting rubbish, but would be worth quickly cross-checking on your end. Thank you!

**Comment by dpiras** [comment]
@Lbalkenhol in the original `CP` papers we used `conv_factor = (2.7255e6)**2` as the conversion factor (see e.g. [here](https://github.com/alessiospuriomancini/cosmopower/blob/cb323858f5567b61d3de71aadb452c95ef908984/notebooks/training_notebooks/cosmopower_NN_CMB_training.ipynb#L982)), although I'll leave it to @borisbolliet @HTJense to confirm it.

**Comment by dpiras** [comment]
Re sigma8, do you mean a model like [this one](https://github.com/cosmopower-organization/jense_2024_emulators/blob/main/jense_2023_camb_mnu_neff/networks/jense_2023_camb_mnu_neff_derived.npz) @Lbalkenhol?

**Comment by HTJense** [comment]
Hi both, thanks a lot for the work that you have done and apologies for not joining in the conversation sooner.

For the emulator loading and usage, we (Ian & I) are working on updating the cosmopower main repository to include our work from the packaging paper (see [this PR](https://github.com/alessiospuriomancini/cosmopower/pull/28)). For the most part the code is there and working if you want to have a look and browse, we "just" need to make new tutorial notebooks and triple-check things before we push it into main.

We switched the network file format from pkl to npz because of previously noted issues with pickle files and future backward-compatiblity (if the restore_network function changes, npz are slightly more robust than pkl files). We haven't changed the actual structure of the files from Alessio's original implementation, just the format it is stored in (cf. [here](https://github.com/HTJense/cosmopower/blob/packaging-paper/cosmopower/cosmopower_NN.py#L287)). I believe Boris has worked to update his emulators to be stored in npz files as well. This should mean it's probably also fine to load the emulators in the same manner in CPJ. Perhaps eventually we can update CPJ to also interface with the packaging prescription, converging the two towards more of a common infrastructure.

The emulators indeed spit out C_ells in dimensionless quantities, and multiplying them by the CMB temperature^2 should give you the normal muK^2 dimensions (cf mimicking camb's behaviour [here](https://github.com/cmbant/CAMB/blob/ecd375bff3cd736b3590a22c8f9663b9e6180ee2/camb/results.py#L363)).

For the sigma8 emulators, Lennart is referring to emulators of sigma8(z) quantities, like [these](https://github.com/cosmopower-organization/mnu/tree/main/growth-and-distances)?

Thanks a lot again for everything you're doing! If there's anything I can help you with, let me know!

**Comment by dpiras** [comment]
Thank you for confirming @HTJense! When I first wrote `CPJ` I assumed the storage format of the loaded model would be the same as the one used in `CP`, so it makes sense that it was failing for @Lbalkenhol. After my [PR ](https://github.com/dpiras/cosmopower-jax/pull/11) yesterday (which I'll merge soon) this incompatibility should have been fixed.

Re the sigma8 models, I was able to load e.g. `jense_2024_emulators/jense_2023_camb_mnu/networks/jense_2023_camb_mnu_sigma8.npz` and run it with `CPJ`, although I don't understand why it is giving out 1000 values? Also, what are the ideal values of these input parameters?
![image](https://github.com/user-attachments/assets/33f4f4a8-f891-4c3c-ada6-ff9adb810deb)


@Lbalkenhol if you could reproduce and share a case where you get weird values like infs, that'd be helpful, thank you!

**Comment by HTJense** [comment]
Hi @dpiras,

The emulators come with a [packaging file](https://github.com/cosmopower-organization/jense_2024_emulators/blob/main/jense_2023_pk_camb_mnu.yaml) that prescribes what the emulator emulates and what parameters it's based on.

In this case, the output is sigma8(z) for 1000 linear steps between z = 0 and z = 5 (cf. lines 96-99).

The parameter ranges for the training input are given in the `parameters` block starting on line 22, so the training ranges are:

```
  parameters:
    ombh2: [0.015,0.030]
    omch2: [0.09,0.15]
    logA: [2.5,3.5]
    ns: [0.85, 1.05]
    h: [0.4,1.0]
    z: [0.0, 5.0]

    A_b: [2.0, 4.0]
    eta_b: [0.5, 1.0]
    logT_AGN: [7.3, 8.3]

    mnu: [0.0, 0.5]
```

So anything within this range should be appropriate values.

**Comment by dpiras** [comment]
Thank you @HTJense! 

What I obtain with `CPJ` for `sigma8` is as in the picture below, 1000 values across redshift, which look good to me. 

![image](https://github.com/user-attachments/assets/4d881693-9a2c-4a7d-8e18-e035ccce89a3)

@Lbalkenhol what do you think?

**Comment by Lbalkenhol** [comment]
Hi all, and thanks again for your work on this, that's great. This all looks good to me. I am about to go offline for a week though - I'll test things on my end when I'm back and confirm with you. Cheers!

**Comment by dpiras** [comment]
Cool, I'll close these issues and merge the PR, feel free to reopen if needed!

**Comment by Lbalkenhol** [comment]
Hi all, coming back to this: Are you able to get something sensible for lensing models too? I'm looking to load @HTJense's into CosmoPower JAX. TT/TE/EE work like a charm after the update and the appropriate conversation factors (thanks again!). For PP I'm getting an okay looking shape, but seems I may be missing a constant offset. It could be a usage issue on my end as well... Thanks in advance!

**Comment by dpiras** [comment]
@Lbalkenhol I get something like this using `jense_2023_camb_mnu/networks/jense_2023_camb_mnu_Cl_bb.npz`, do you also get this? Which units or scale are expected?

Maybe you referred to `jense_2023_camb_mnu_Cl_pp.npz` though, let me check that too.

![image](https://github.com/user-attachments/assets/24656c49-f17f-43d8-b4ea-8e91765ea4b3)

**Comment by dpiras** [comment]
And this is what I get for PP, indeed it seems that the units are different (a missing exp?); also, I had to remove `tau` from the parameters.

@HTJense, @borisbolliet is this expected? And which prefactors were used to rescale the spectra?

![image](https://github.com/user-attachments/assets/f5564f6c-b2b3-4fdf-ae26-993e5f804ac7)

**Comment by HTJense** [comment]
Hi both,

I indeed did not use tau as an input for the lensing power spectra (cf. see [this line](https://github.com/cosmopower-organization/jense_2024_emulators/blob/main/jense_2023_cmb_camb_mnu.yaml#L120) in the prescription file).

The prefactor for the PP emulator should be (ell * (ell + 1))^2 / 2 pi, since that's what [camb](https://camb.readthedocs.io/en/latest/results.html#camb.results.CAMBdata.get_lens_potential_cls) computes - although I am current doubting my own implementation of this so please let me know if this is correct 😅.

**Comment by dpiras** [comment]
Thank you @HTJense! So something like this?

![image](https://github.com/user-attachments/assets/1f3f21a6-96b0-4b8e-a311-0bdeea39c86e)

**Comment by dpiras** [comment]
Like this? (I think I'm having some overflow issues...)
![image](https://github.com/user-attachments/assets/f1b6a21d-48dc-4a3c-a5d9-a7570aa9536c)

**Comment by HTJense** [comment]
Hmm, so the emulator has the prefactor baked in, so you should just plot `plt.plot(ell, prediction)` and that should be with the (l (l+1))^2 / 2 pi prefactor included. The units are dimensionless, so you should get something that peaks around 10^-7 in D_ells.

**Comment by dpiras** [comment]
Right, so we get back to the previous plot, which seems to have [-10 -7] in the y-range though, so perhaps a missing exponential here (that was not needed for the other models)?
![image](https://github.com/user-attachments/assets/dff45bc4-4b27-4ff9-9353-d80cc8f1dc51)

**Comment by Lbalkenhol** [comment]
Thanks for jumping on this so quickly! @dpiras yes that's exactly what I get with the `.npz` files

**Comment by HTJense** [comment]
@dpiras Right, so the TT and EE emulators were 'custom_log' types, which were automatically taken to be 10^predictions, whereas the TE emulator (which was 'custom_pca' type) was emulated directly. For the pp emulator, we used both PCA compression and we emulated the log-quantities instead of the quantities directly. I think that is done differently here?

**Comment by dpiras** [comment]
Right, so for @Lbalkenhol it is just sufficient to take `10**prediction`, as in the screenshot?
![image](https://github.com/user-attachments/assets/9bfd9b2b-2029-48fb-9383-26d668d7dfe7)

**Comment by dpiras** [comment]
@HTJense @Lbalkenhol let me know if this makes sense, I'm closing the issue so far but feel free to reopen!
